apiVersion: v1
kind: Secret
metadata:
  name: server
  namespace: boardgames
  labels:
    app.boardgames.churners.network/name: server
data:
  config.yml: d2ViOgogIHBvcnQ6IDgwODAKCnRsczogCiAgY2VydEZpbGU6IC92YXIvdGxzLWNlcnRzL3Rscy5jcnQKICBrZXlGaWxlOiAvdmFyL3Rscy1jZXJ0cy90bHMua2V5

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  namespace: boardgames

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: boardgames
  labels:
    app.boardgames.churners.network/name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.boardgames.churners.network/name: server
      app-instance: server
  template:
    metadata:
      labels:
        app.boardgames.churners.network/name: server
        app-instance: server
    spec:
      volumes:
      - name: certs
        secret: 
          secretName: external-wildcard
      - name: config
        secret: 
          secretName: server
      serviceAccountName: server
      containers:
      - name: boardgames
        image: kube-registry:5000/boardgames:latest
        args:
        - --file
        - /var/config/config.yml
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: certs
          mountPath: /var/tls-certs
        - name: config
          mountPath: /var/config

---

apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: boardgames
  annotations:
    tailscale.com/expose: "true"
  labels:
    app.boardgames.churners.network/name: server
spec:
  selector:
    app.boardgames.churners.network/name: server
    app-instance: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

